# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161104_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bd',
            name='Numerotelephone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bd',
            name='Profession',
            field=models.CharField(choices=[('P', 'Professeur'), ('E', 'Etudiant')], default='E', max_length=1),
        ),
    ]
